apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xi2v
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-xi2v@sha256:6091355e3af09d9e5e255f07b4035e51a991a6a7dbddbf6111cc5dcf5012e39b
        name: my-nodejs
        resources: {}
status: {}
